/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class water_is_dangerous_Crash */

#ifndef _Included_water_is_dangerous_Crash
#define _Included_water_is_dangerous_Crash
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     water_is_dangerous_Crash
 * Method:    crash
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_water_1is_1dangerous_Crash_crash
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
